
server:
  port: 8082

logging:
  level:
    org:
      flywaydb: DEBUG
    com.ead: TRACE
    root: INFO

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost