
server:
  port: 8082

logging:
  level:
    org:
      flywaydb: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none