
server:
  port: 8082

logging:
  level:
    org:
      flywaydb: DEBUG
    com.ead: TRACE
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

ead:
  api:
    url:
      authuser: 'http://localhost:8087'